version: '2'
services:
  ww_hackathon_team2-app:
    image: ww_hackathon_team2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://ww_hackathon_team2-mysql:3306/ww_hackathon_team2?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  ww_hackathon_team2-mysql:
    extends:
      file: mysql.yml
      service: ww_hackathon_team2-mysql
