apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  labels:
    app: jhipster-app
spec:
  rules:
    - host: team-2.homek8s.dev
      http:
        paths:
          - backend:
              serviceName: app-service
              servicePort: http
            path: /
  tls:
    - hosts:
        - team-2.homek8s.dev
      secretName: app-ingress-cert
