apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: WWpjeE5qTmtObU14WmpJNE1URTBZamczWW1WaE5EWmlaak16WmpGa01XUXpORE15WldFeVlURTVOREE0TjJVMFkyTmpZVEZsWVRkaU4yVXpPRFk1WVdNNE5HVmtOV0pqTlRBell6ZGxOVE5sT0dabU1EWmpZakU1TjJFMVkySm1ZbU5sTkdSbE9EQXpOamd5WVdaaE5EYzBOREk0WlRaaVlqQTRNVGc0TW1NPQ==
