apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: jhipster-app
spec:
  selector:
    app: jhipster-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
